### ISSUE TITLE
Afbeelding frontpage

### ISSUE THREAD

**Issue by reithose** [geensnor/DigitaleTuin#14]
Ik zou wel een mooie (rechtevrije!!) afbeelding op de frontpage willen hebben. Maar die zijn nog niet zo makkelijk te vinden...

**Comment by Zuijdam** [comment]
Wat voor iets denk je aan?

**Comment by reithose** [comment]
Iets tuinerigs. Misschien met knipoog. Originele invalshoek. Dat werk een beetje...

**Comment by reithose** [comment]
https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Garden_of_Earthly_Delights_002.jpg/640px-Garden_of_Earthly_Delights_002.jpg

deze?

**Comment by reithose** [comment]
Of anders iets van de post-impressionisten
![van gogh](https://mdl.artvee.com/sftb/506790ld.jpg)
![Cézanne](https://user-images.githubusercontent.com/6649052/142227106-496500fa-3419-4b5b-ac00-700a511ba2e6.png)

**Comment by Zuijdam** [comment]
https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Monet_Luncheon.jpg/1200px-Monet_Luncheon.jpg zoiets?

**Comment by reithose** [comment]
We hebben na jaren zoeken eindelijk iets gevonden wat ons bevalt: https://github.com/geensnor/DigitaleTuin/commit/cde582253a2d447c1bec9083a356c3626f4d66e5
