### ISSUE TITLE
Wielrennen overtreedt regel MD034

### ISSUE THREAD

**Issue by reithose** [geensnor/DigitaleTuin#44]
De URL's van de podcast overtreden regel MD034 van de linter. 15 keer zelfs
https://github.com/DavidAnson/markdownlint/blob/v0.33.0/doc/md034.md

**Comment by Zuijdam** [comment]
Ja klopt. Ook al heel lang trouwens

**Comment by reithose** [comment]
owjee, ik zie het inderdaad. Wat een puinhoop. Ik heb direct de linter wat strakker gezet.
