### ISSUE TITLE
De pagina waarop de streetviews staan, werkt niet helemaal goed

### ISSUE THREAD

**Issue by reithose** [geensnor/DigitaleTuin#53]
Kijk maar...
<img width="835" alt="afbeelding" src="https://github.com/user-attachments/assets/1ac81daa-f01a-4ce9-b241-2881c17dd4fa">

**Comment by Zuijdam** [comment]
Ja klopt, daarom zie PR

**Comment by reithose** [comment]
Ja, ik heb hem er ook aan gekoppeld.
